* Overall project goals

** Document the assembler

** Document the compiler

** Document undocumented functions

* Code known to be reviewed

** ikarus.io.ss

   Solve all the FIXME issues

   If SET-PORT-POSITION!  fails it is  possible for the field POS of the
   cookie to become invalid.  Should the port be marked as corrupted?

   Functions still to be reviewed:

	tcp-connect tcp-connect-nonblocking
	udp-connect udp-connect-nonblocking
	tcp-server-socket tcp-server-socket-nonblocking
	accept-connection accept-connection-nonblocking
	close-tcp-server-socket
	register-callback

* Miscellaneous stuff to be fixed

  NATIVE-ENDIANNESS in "ikarus.bytevectors.ss" has a hard coded value of
  LITTLE.

* List of functions to be documented

  Some of  these may  be internal functions  which must be  removed from
  "makefile.sps".  Not  all the undocumented functions  are listed here,
  only the ones known not to be documented.

** low level

   $flonum-sbe
   top-level-value
   $init-symbol-function!

** ikarus.symbols.ss

   gensym-count
   top-level-value top-level-bound? set-top-level-value!
   symbol-value symbol-bound? set-symbol-value!
   reset-symbol-proc! system-value system-value-gensym


** ikarus.io.ss

   reset-input-port!
   reset-output-port!

* end

### end of file
# Local Variables:
# coding: utf-8-unix
# End:
