* Overall project goals

** Document the assembler

** Document the compiler

** Document undocumented functions

* Code known to be reviewed

** ikarus.io.sls

   Solve all the FIXME issues

   If SET-PORT-POSITION!  fails it is  possible for the field POS of the
   cookie to become invalid.  Should the port be marked as corrupted?

** list of C code that must be reviewed

*** ikarus-numerics.c

    Only partially  reviewed.  From "ikrt_bnbnplus()"  on, the functions
    must be reviewed using the C preprocessor macros in the header file.
    Tests for the functions must go in "test-vicare-bignums.sps".

* Miscellaneous stuff to be fixed

** ikarus.symbols.ss

   The name of  generated symbols embeds a numeric  counter which is the
   stringification of a fixnum.   What if generating many symbols causes
   the counter to overflow the fixnums?

* List of functions to be tested

  The flonum getters  and setters in the bytevector  library should have
  tests in "test-vicare-bytevectors.sps".

* Documentation

  The documentation node "capi" should  be fully reviewed.  Does it make
  sense to have  it at all?  Would  it be better to just  document the C
  functions in the source code?

* Stuff to think about for the future

** glibc interesting functions

*** asynchronous input/output

    Could it work with Vicare?

** Introduce immutable datums

   Strings  and  bytevectors  read   from  the  source  code  should  be
   immutable.

** Linux interesting functions

* end

### end of file
# Local Variables:
# coding: utf-8-unix
# End:
