* Overall project goals

** Document the assembler

** Document the compiler

** Document undocumented functions

* Code known to be reviewed

** ikarus.io.ss

   Solve all the FIXME issues

   If SET-PORT-POSITION!  fails it is  possible for the field POS of the
   cookie to become invalid.  Should the port be marked as corrupted?

   Functions still to be reviewed:

	tcp-connect tcp-connect-nonblocking
	udp-connect udp-connect-nonblocking
	tcp-server-socket tcp-server-socket-nonblocking
	accept-connection accept-connection-nonblocking
	close-tcp-server-socket
	register-callback

** list of files still to review

   scheme/ikarus.enumerations.ss
   scheme/ikarus.pointers.ss
   scheme/ikarus.numerics.ss
   scheme/ikarus.conditions.ss
   scheme/ikarus.cafe.ss
   scheme/ikarus.records.procedural.ss

   scheme/ikarus.posix.ss
   scheme/ikarus.exceptions.ss
   scheme/ikarus.debugger.ss

   scheme/ikarus.code-objects.ss
   scheme/ikarus.collect.ss
   scheme/ikarus.control.ss
   scheme/ikarus.date-string.ss
   scheme/ikarus.equal.ss
   scheme/ikarus.fasl.ss
   scheme/ikarus.fasl.write.ss
   scheme/ikarus.fixnums.ss
   scheme/ikarus.handlers.ss
   scheme/ikarus.hash-tables.ss
   scheme/ikarus.multiple-values.ss
   scheme/ikarus.pretty-formats.ss
   scheme/ikarus.pretty-print.ss
   scheme/ikarus.singular-objects.ss
   scheme/ikarus.sort.ss
   scheme/ikarus.time-and-date.ss
   scheme/ikarus.timer.ss
   scheme/ikarus.unicode-conversion.ss
   scheme/ikarus.unicode.ss
   scheme/ikarus.writer.ss

   scheme/ikarus.compiler.ss
   scheme/ikarus.compiler.altcogen.ss
   scheme/ikarus.compiler.ontology.ss
   scheme/ikarus.compiler.optimize-letrec.ss
   scheme/ikarus.compiler.source-optimizer.ss
   scheme/ikarus.compiler.tag-annotation-analysis.ss
   scheme/pass-specify-rep.ss
   scheme/pass-specify-rep-primops.ss
   scheme/ikarus.intel-assembler.ss

   scheme/psyntax.builders.ss
   scheme/psyntax.compat.ss
   scheme/psyntax.config.ss
   scheme/psyntax.expander.ss
   scheme/psyntax.internal.ss
   scheme/psyntax.library-manager.ss

** list of files that maybe will be reviewed

   scheme/x86-64-repl.ss

* Miscellaneous stuff to be fixed

** ikarus.symbols.ss

   The name of  generated symbols embeds a numeric  counter which is the
   stringification of a fixnum.   What if generating many symbols causes
   the counter to overflow the fixnums?

* List of functions to be documented

  Some of  these may  be internal functions  which must be  removed from
  "makefile.sps".  Not  all the undocumented functions  are listed here,
  only the ones known not to be documented.

** low level

   $flonum-sbe
   $init-symbol-function!

** ikarus.symbols.ss

   gensym-count
   top-level-value top-level-bound? set-top-level-value!
   reset-symbol-proc! system-value system-value-gensym

** ikarus.io.ss

   reset-input-port!
   reset-output-port!

* List of functions to be tested

  The flonum getters  and setters in the bytevector  library should have
  tests in "test-vicare-bytevectors.sps".

* end

### end of file
# Local Variables:
# coding: utf-8-unix
# End:
