@node iqueues
@chapter Interface to queue--like containers


@cindex @library{vicare containers iqueues}, library
@cindex Library @library{vicare containers iqueues}


The library @library{vicare containers iqueues} implements a common
@api{} for queue--like containers: data structure capable of
first--in/first--out operations.  A data structure is queue--like if it
implements the operations: @samp{empty?}, @samp{top}, @samp{push!},
@samp{pop!}.



@c Local Variables:
@c mode: texinfo
@c TeX-master: "vicare-libs"
@c End:
