@node strings
@chapter Extended strings processing


@cindex Library @library{nausicaa containers strings}
@cindex @library{nausicaa containers strings}, library


The label @class{xstring} provides an interface to the functions in
@library{vicare containers strings} through the facilities of the
language @library{nausicaa}.


@deftp Label @aclass{xstring}
Label interface to the extended string functions.  It is derived from
@class{string}.
@end deftp


All the following methods are implemented as syntaxes; in all the
following descriptions: @var{self} is an identifier bound to the subject
string.

@c ------------------------------------------------------------

@macro XstringMethod{NAME}
@defmethod @aclass{xstring} \NAME\ . @var{args}
Implement the expansion:

@example
(@var{self} \NAME\ . @var{args})
@expansion{} (string-\NAME\ @var{self} . @var{args})
@end example
@end defmethod
@end macro

@macro XstringMethodNoPrefix{NAME}
@defmethod @aclass{xstring} \NAME\ . @var{args}
Implement the expansion:

@example
(@var{self} \NAME\ . @var{args})
@expansion{} (\NAME\ @var{self} . @var{args})
@end example
@end defmethod
@end macro

@macro XstringMethodCompare{NAME}
@defmethod @aclass{xstring} \NAME\ @var{item=} . @var{args}
Implement the expansion:

@example
(@var{self} \NAME\ @var{item=} . @var{args})
@expansion{} (string\NAME\ @var{item=} @var{self} . @var{args})
@c                 *^*
@end example
@end defmethod
@end macro

@macro XstringMethodMap{NAME}
@defmethod @aclass{xstring} \NAME\ @var{proc} . @var{args}
Implement the expansion:

@example
(@var{self} \NAME\ @var{proc} . @var{args})
@expansion{} (string-\NAME\ @var{proc} @var{self} . @var{args})
@end example
@end defmethod
@end macro

@macro XstringMethodMapNoPrefix{NAME}
@defmethod @aclass{xstring} \NAME\ @var{proc} . @var{args}
Implement the expansion:

@example
(@var{self} \NAME\ @var{proc} . @var{args})
@expansion{} (\NAME\ @var{proc} @var{self} . @var{args})
@end example
@end defmethod
@end macro

@macro XstringMethodFold{NAME}
@defmethod @aclass{xstring} \NAME\ @var{kons} @var{knil} . @var{args}
Implement the expansion:

@example
(@var{self} \NAME\ @var{kons} @var{knil} . @var{args})
@expansion{} (string-\NAME\ @var{kons} @var{knil} @var{self} . @var{args})
@end example
@end defmethod
@end macro

@macro XstringMethodFoldNoPrefix{NAME}
@defmethod @aclass{xstring} \NAME\ @var{kons} @var{knil} . @var{args}
Implement the expansion:

@example
(@var{self} \NAME\ @var{kons} @var{knil} . @var{args})
@expansion{} (\NAME\ @var{kons} @var{knil} @var{self} . @var{args})
@end example
@end defmethod
@end macro


@c ------------------------------------------------------------

@subsubheading Constructors

@defmethod @aclass{xstring} concatenate @var{list-of-strings}
Implement the expansion:

@example
(@var{self} concatenate @var{list-of-strings})
@expansion{} (string-concatenate (cons @var{self} @var{list-of-strings}))
@end example
@end defmethod


@defmethod @aclass{xstring} concatenate-reverse @var{list-of-strings}
@defmethodx @aclass{xstring} concatenate-reverse @var{list-of-strings} @var{final-string}
@defmethodx @aclass{xstring} concatenate-reverse @var{list-of-strings} @var{final-string} @var{nvalues}
Implement the expansions:

@example
(@var{self} concatenate-reverse @var{list-of-strings})
@expansion{} (string-concatenate-reverse
     (cons @var{self} @var{list-of-strings}))

(@var{self} concatenate-reverse @var{list-of-strings}
                          @var{final-string})
@expansion{} (string-concatenate-reverse
     (cons @var{self} @var{list-of-strings})
     @var{final-string})

(@var{self} concatenate-reverse @var{list-of-strings}
                          @var{final-string} @var{nvalues})
@expansion{} (string-concatenate-reverse
     (cons @var{self} @var{list-of-strings})
     @var{final-string} @var{nvalues})
@end example
@end defmethod

@c ------------------------------------------------------------

@subsubheading Predicates

@XstringMethod{null?}
@XstringMethodMap{every}
@XstringMethodMap{any}

@c ------------------------------------------------------------

@subsubheading Comparison

@XstringMethod{compare}
@XstringMethodCompare{=}
@XstringMethodCompare{<>}
@XstringMethodCompare{<}
@XstringMethodCompare{<=}
@XstringMethodCompare{>}
@XstringMethodCompare{>=}
@XstringMethod{compare-ci}
@XstringMethod{ci=}
@XstringMethod{ci<>}
@XstringMethod{ci<}
@XstringMethod{ci<=}
@XstringMethod{ci>}
@XstringMethod{ci>=}

@c ------------------------------------------------------------

@subsubheading Dictionary comparison

@XstringMethod{dictionary-compare}
@XstringMethod{dictionary=?}
@XstringMethod{dictionary<>?}
@XstringMethod{dictionary<?}
@XstringMethod{dictionary<=?}
@XstringMethod{dictionary>?}
@XstringMethod{dictionary>=?}
@XstringMethod{dictionary-compare-ci}
@XstringMethod{dictionary-ci=?}
@XstringMethod{dictionary-ci<>?}
@XstringMethod{dictionary-ci<?}
@XstringMethod{dictionary-ci<=?}
@XstringMethod{dictionary-ci>?}
@XstringMethod{dictionary-ci>=?}

@c ------------------------------------------------------------

@subsubheading String/numbers lexicographic comparison

@XstringMethodNoPrefix{string/numbers-compare}
@XstringMethodNoPrefix{string/numbers=?}
@XstringMethodNoPrefix{string/numbers<>?}
@XstringMethodNoPrefix{string/numbers<?}
@XstringMethodNoPrefix{string/numbers<=?}
@XstringMethodNoPrefix{string/numbers>?}
@XstringMethodNoPrefix{string/numbers>=?}
@XstringMethodNoPrefix{string/numbers-compare-ci}
@XstringMethodNoPrefix{string/numbers-ci=?}
@XstringMethodNoPrefix{string/numbers-ci<>?}
@XstringMethodNoPrefix{string/numbers-ci<?}
@XstringMethodNoPrefix{string/numbers-ci>?}
@XstringMethodNoPrefix{string/numbers-ci<=?}
@XstringMethodNoPrefix{string/numbers-ci>=?}

@c ------------------------------------------------------------

@subsubheading String/numbers dictionary comparison

@XstringMethodNoPrefix{string/numbers-dictionary-compare}
@XstringMethodNoPrefix{string/numbers-dictionary=?}
@XstringMethodNoPrefix{string/numbers-dictionary<>?}
@XstringMethodNoPrefix{string/numbers-dictionary<?}
@XstringMethodNoPrefix{string/numbers-dictionary<=?}
@XstringMethodNoPrefix{string/numbers-dictionary>?}
@XstringMethodNoPrefix{string/numbers-dictionary>=?}
@XstringMethodNoPrefix{string/numbers-dictionary-compare-ci}
@XstringMethodNoPrefix{string/numbers-dictionary-ci=?}
@XstringMethodNoPrefix{string/numbers-dictionary-ci<>?}
@XstringMethodNoPrefix{string/numbers-dictionary-ci<?}
@XstringMethodNoPrefix{string/numbers-dictionary-ci>?}
@XstringMethodNoPrefix{string/numbers-dictionary-ci<=?}
@XstringMethodNoPrefix{string/numbers-dictionary-ci>=?}

@c ------------------------------------------------------------

@subsubheading Mapping

@XstringMethodMap{map}
@XstringMethodMap{map!}
@XstringMethodMap{map*}
@XstringMethodMap{map*!}
@XstringMethodMap{for-each*}
@XstringMethodMapNoPrefix{substring-map}
@XstringMethodMapNoPrefix{substring-map!}
@XstringMethodMapNoPrefix{substring-for-each}
@XstringMethodMapNoPrefix{substring-for-each-index}

@c ------------------------------------------------------------

@subsubheading Case

@XstringMethod{downcase*}
@XstringMethod{upcase*}
@XstringMethod{titlecase*}
@XstringMethod{downcase*!}
@XstringMethod{upcase*!}
@XstringMethod{titlecase*!}

@c ------------------------------------------------------------

@subsubheading Folding

@XstringMethodFold{fold-left}
@XstringMethodFold{fold-right}
@XstringMethodFold{fold-left*}
@XstringMethodFold{fold-right*}
@XstringMethodFoldNoPrefix{substring-fold-left}
@XstringMethodFoldNoPrefix{substring-fold-right}

@c ------------------------------------------------------------

@subsubheading Selecting

@XstringMethodNoPrefix{substring*}
@XstringMethod{reverse-copy*}
@XstringMethod{copy*!}
@XstringMethod{reverse-copy*!}
@XstringMethod{take}
@XstringMethod{take-right}
@XstringMethod{drop}
@XstringMethod{drop-right}

@c ------------------------------------------------------------

@subsubheading Padding and trimming

@XstringMethod{trim}
@XstringMethod{trim-right}
@XstringMethod{trim-both}
@XstringMethod{pad}
@XstringMethod{pad-right}

@c ------------------------------------------------------------

@subsubheading Prefix and suffix

@XstringMethod{prefix-length}
@XstringMethod{prefix-length-ci}
@XstringMethod{suffix-length}
@XstringMethod{suffix-length-ci}
@XstringMethod{prefix?}
@XstringMethod{prefix-ci?}
@XstringMethod{suffix?}
@XstringMethod{suffix-ci?}

@c ------------------------------------------------------------

@subsubheading Searching

@XstringMethod{index}
@XstringMethod{index-right}
@XstringMethod{skip}
@XstringMethod{skip-right}
@XstringMethod{contains}
@XstringMethod{contains-ci}
@XstringMethod{count}

@c ------------------------------------------------------------

@subsubheading Filtering

@XstringMethod{filter}
@XstringMethod{delete}

@c ------------------------------------------------------------

@subsubheading Lists

@defmethod @aclass{xstring} list* . @var{args}
Implement the expansion:

@example
(@var{self} list* . @var{args})
@expansion{} (string->list* @var{self} . @var{args})
@end example
@end defmethod


@defmethod @aclass{xstring} join @var{list-of-strings} . @var{args}
Implement the expansion:

@example
(@var{self} join @var{list-of-strings} . @var{args})
@expansion{} (string-join (cons @var{self} @var{list-of-strings}) . @var{args})
@end example
@end defmethod


@XstringMethod{tokenize}
@XstringMethod{tokenise}

@c ------------------------------------------------------------

@subsubheading Replicating

@XstringMethodNoPrefix{xsubstring}
@XstringMethod{xcopy!}

@c ------------------------------------------------------------

@subsubheading Mutating

@XstringMethod{fill*!}
@XstringMethod{swap!}

@c ------------------------------------------------------------

@subsubheading Reverse and replace

@XstringMethod{reverse}
@XstringMethod{reverse!}
@XstringMethod{replace}



@c end of file
