#!/bin/sh
#
# Rebuild the "./src/last-revision.h" file holding the branch and
# commit hash.  To be run from the top source directory.
#
# This script  can be  run by adding  the following line  at the  end of
# "$(top_srcdir)/.git/hooks/post-commit":
#
#   sh ./scripts/make-last-revision
#

PATH=~/bin:${PATH}

LAST_REVISION_FILE=./src/last-revision.h
BRANCH_NAME=$(git branch 2>/dev/null | sed -e '/^[^*]/d' -e 's/^* //')
COMMIT_HASH=$(git show | head -1 | cut -d' ' -f2)
echo "#define LAST_REVISION \"$BRANCH_NAME/$COMMIT_HASH\"" >$LAST_REVISION_FILE

### end of file

